# Site settings
title: Jaeheon's Portfolio
description: Jaeheon's Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://backendhoney.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Jaeheon Lee"
user_description: 
user_title: back-end Developer
email: ti6419@gmail.com
github_username: backendhoney


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
